//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/InputActions/PlayerIM.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GGJ2026
{
    public partial class @PlayerIM: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerIM()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerIM"",
    ""maps"": [
        {
            ""name"": ""P1"",
            ""id"": ""dd4f54b4-9498-4b1c-9a0e-67faf02ee554"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f2589be6-a61d-47c1-99bf-10646c40de17"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1c6aa05c-fd51-4be2-838f-c52a8a1f978b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""d04e3b96-2f7f-4d56-b5e4-41d194f8ddbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""P1Move"",
                    ""id"": ""5424be40-20be-4de7-8b43-364b9d71659b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d686873-30d6-4e8d-8833-c2847ad7f77e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7d80cf20-de2f-41f1-8e37-4d0caeead47c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6019b6b5-f116-4ac8-b0b6-a8a77bbbb37c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c5bfae4d-1b93-4738-a0d6-7bde06a77685"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a5900fdc-24e9-418d-a859-953b5db2cb3f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1234567-89ab-cdef-0123-456789abcdef"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e09b14b2-e33e-4400-b550-ab5ee1268bdb"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2345678-90ab-cdef-0123-456789abcdef"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""P2"",
            ""id"": ""c05634a0-6574-401e-8ad0-3c377608f4dd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d744241c-8fce-4d44-9cc6-d335509604f6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""31bd28c8-3dc7-4686-bf29-796134634eed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""cfad18e2-324e-490b-9b2a-4edf11dc50c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""P2Move"",
                    ""id"": ""57578ebf-7d96-4b4c-8799-cc12bc7294c8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d589c753-a10d-483b-a751-441efc69e287"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ce29657e-d8b0-43b9-a8e8-308f7aa58ac3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47a97183-da6e-4179-a801-6592eff3cd31"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9bd09151-b884-4eb0-8315-e49b2709bbe1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f8e79187-dcc9-47b6-9d61-8f3ba65460f5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2116530-494e-45ab-992f-4fcc92219c86"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // P1
            m_P1 = asset.FindActionMap("P1", throwIfNotFound: true);
            m_P1_Move = m_P1.FindAction("Move", throwIfNotFound: true);
            m_P1_Jump = m_P1.FindAction("Jump", throwIfNotFound: true);
            m_P1_Dash = m_P1.FindAction("Dash", throwIfNotFound: true);
            // P2
            m_P2 = asset.FindActionMap("P2", throwIfNotFound: true);
            m_P2_Move = m_P2.FindAction("Move", throwIfNotFound: true);
            m_P2_Jump = m_P2.FindAction("Jump", throwIfNotFound: true);
            m_P2_Dash = m_P2.FindAction("Dash", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // P1
        private readonly InputActionMap m_P1;
        private List<IP1Actions> m_P1ActionsCallbackInterfaces = new List<IP1Actions>();
        private readonly InputAction m_P1_Move;
        private readonly InputAction m_P1_Jump;
        private readonly InputAction m_P1_Dash;
        public struct P1Actions
        {
            private @PlayerIM m_Wrapper;
            public P1Actions(@PlayerIM wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_P1_Move;
            public InputAction @Jump => m_Wrapper.m_P1_Jump;
            public InputAction @Dash => m_Wrapper.m_P1_Dash;
            public InputActionMap Get() { return m_Wrapper.m_P1; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(P1Actions set) { return set.Get(); }
            public void AddCallbacks(IP1Actions instance)
            {
                if (instance == null || m_Wrapper.m_P1ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_P1ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
            }

            private void UnregisterCallbacks(IP1Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @Dash.started -= instance.OnDash;
                @Dash.performed -= instance.OnDash;
                @Dash.canceled -= instance.OnDash;
            }

            public void RemoveCallbacks(IP1Actions instance)
            {
                if (m_Wrapper.m_P1ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IP1Actions instance)
            {
                foreach (var item in m_Wrapper.m_P1ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_P1ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public P1Actions @P1 => new P1Actions(this);

        // P2
        private readonly InputActionMap m_P2;
        private List<IP2Actions> m_P2ActionsCallbackInterfaces = new List<IP2Actions>();
        private readonly InputAction m_P2_Move;
        private readonly InputAction m_P2_Jump;
        private readonly InputAction m_P2_Dash;
        public struct P2Actions
        {
            private @PlayerIM m_Wrapper;
            public P2Actions(@PlayerIM wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_P2_Move;
            public InputAction @Jump => m_Wrapper.m_P2_Jump;
            public InputAction @Dash => m_Wrapper.m_P2_Dash;
            public InputActionMap Get() { return m_Wrapper.m_P2; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(P2Actions set) { return set.Get(); }
            public void AddCallbacks(IP2Actions instance)
            {
                if (instance == null || m_Wrapper.m_P2ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_P2ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
            }

            private void UnregisterCallbacks(IP2Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @Dash.started -= instance.OnDash;
                @Dash.performed -= instance.OnDash;
                @Dash.canceled -= instance.OnDash;
            }

            public void RemoveCallbacks(IP2Actions instance)
            {
                if (m_Wrapper.m_P2ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IP2Actions instance)
            {
                foreach (var item in m_Wrapper.m_P2ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_P2ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public P2Actions @P2 => new P2Actions(this);
        public interface IP1Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnDash(InputAction.CallbackContext context);
        }
        public interface IP2Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnDash(InputAction.CallbackContext context);
        }
    }
}
